name: Inline Scripts and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install beautifulsoup4 requests

    - name: Inline scripts in HTML file
      run: |
        HTML_FILE="p2pchat.html"
        python scripts/inline-scripts.py $HTML_FILE

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          Changes in this release:
          - Inline scripts in HTML file

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: path/to/inlined-file.html
        asset_name: inlined-file.html
        asset_content_type: text/html
